In [23]:

import pandas as pd
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')
import seaborn as sns
import numpy as np

# Load the dataset
file_path = 'Daily activity metrics copy.csv'
data = pd.read_csv(file_path)

# # Convert 'Date' column to datetime format for consistency in time-based analysis
# data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')

In [24]:
data.columns

Index(['Date', 'Move Minutes count', 'Calories (kcal)', 'Distance (m)',
       'Average heart rate (bpm)', 'Max heart rate (bpm)',
       'Min heart rate (bpm)', 'Average speed (m/s)', 'Max speed (m/s)',
       'Min speed (m/s)', 'Step count', 'Walking duration (ms)'],
      dtype='object')

In [25]:
from sklearn.linear_model import LinearRegression

# Drop rows with missing values in any of the three columns to train the model
complete_data = data.dropna(subset=['Move Minutes count', 'Calories (kcal)', 'Distance (m)',
       'Average heart rate (bpm)', 'Max heart rate (bpm)',
       'Min heart rate (bpm)', 'Average speed (m/s)', 'Max speed (m/s)',
       'Min speed (m/s)', 'Step count', 'Walking duration (ms)'])

In [26]:
# Define the features and target variable
features = complete_data[['Move Minutes count', 'Calories (kcal)', 'Distance (m)',
                                            'Average heart rate (bpm)', 'Max heart rate (bpm)',
                                            'Min heart rate (bpm)', 'Average speed (m/s)', 'Max speed (m/s)',
                                            'Min speed (m/s)', 'Step count']]
target = complete_data['Walking duration (ms)']

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(features, target)

LinearRegression()

In [27]:
# Predict missing calories
missing_calories_data = data[data['Walking duration (ms)'].isna()]
missing_features = missing_calories_data[['Move Minutes count', 'Calories (kcal)', 'Distance (m)',
	'Average heart rate (bpm)', 'Max heart rate (bpm)',
	'Min heart rate (bpm)', 'Average speed (m/s)', 'Max speed (m/s)',
	'Min speed (m/s)', 'Step count']]

# Ensure there are no missing values in the features
missing_features = missing_features.dropna()

# Predict the calories for the rows with complete feature data
predicted_calories = model.predict(missing_features)

# Make negative values positive
predicted_calories = np.abs(predicted_calories)
print(predicted_calories)
# Fill the missing values in the original dataset
data.loc[missing_features.index, 'Walking duration (ms)'] = predicted_calories

# Verify the filled data
data.head(10)

[1294051.34039488 1265334.14125372  309336.36038932 1025847.93500038
  934927.35174192  812847.13574333 1282629.42909263  799740.82646411
   62061.60409918  816729.06775798  723906.80192624  436887.54020062
  364826.96679287  363058.01175768   17367.93486116   11463.54393316
  339435.95431114  343663.08672214  112236.69119503  147371.80846545
   51454.05734811  508747.7325131   477269.41738794  720230.34127842
  636164.18367921  620342.42520983  176606.69206658 1070008.02348257
 1009394.15683218 1431232.73643935   40960.71590418   87574.2703384 ]

,Date,Move Minutes count,Calories (kcal),Distance (m),Average heart rate (bpm),Max heart rate (bpm),Min heart rate (bpm),Average speed (m/s),Max speed (m/s),Min speed (m/s),Step count,Walking duration (ms)
0,12-08-2024,181.0,1454.5,4389.756115,88.933775,115.0,66.0,0.386543,0.478343,0.324931,10244.0,1.294051e+06
1,13-08-2024,180.0,1454.5,4193.930564,83.816770,105.0,66.0,0.415036,0.509161,0.313160,11040.0,1.265334e+06
2,14-08-2024,60.0,1454.5,1700.920657,85.792398,127.0,67.0,0.469593,0.469593,0.469593,10810.0,3.093364e+05
3,15-08-2024,61.0,1454.5,3015.839024,79.345745,118.0,57.0,0.417125,0.540696,0.293554,8100.0,1.025848e+06
4,17-08-2024,61.0,1454.5,1317.428951,84.850410,105.0,62.0,0.355202,0.355202,0.355202,8975.0,9.349274e+05
5,21-08-2024,61.0,1454.5,2932.989752,87.556738,117.0,69.0,0.403163,0.524185,0.282142,9886.0,8.128471e+05
6,22-08-2024,60.0,1454.5,1577.902041,92.114094,111.0,67.0,0.434965,0.434965,0.434965,4164.0,1.282629e+06
7,23-08-2024,NaN,1454.5,1038.126482,86.245370,112.0,67.0,0.289687,0.289687,0.289687,8372.0,NaN
8,24-08-2024,60.0,1454.5,3244.302168,88.168269,119.0,65.0,0.450110,0.629579,0.270641,9759.0,7.997408e+05
9,26-08-2024,60.0,1454.5,2885.916302,96.461538,116.0,65.0,0.400120,0.521693,0.278546,14663.0,6.206160e+04

In [28]:
data.isna().sum()

Date                        1
Move Minutes count          3
Calories (kcal)             1
Distance (m)                1
Average heart rate (bpm)    1
Max heart rate (bpm)        1
Min heart rate (bpm)        1
Average speed (m/s)         1
Max speed (m/s)             1
Min speed (m/s)             1
Step count                  1
Walking duration (ms)       3
dtype: int64

In [29]:
#Save the DataFrame to a CSV file
data.to_csv('Daily_Activity_metrics_filled3.csv', index=False)

In [30]:
data.head()

,Date,Move Minutes count,Calories (kcal),Distance (m),Average heart rate (bpm),Max heart rate (bpm),Min heart rate (bpm),Average speed (m/s),Max speed (m/s),Min speed (m/s),Step count,Walking duration (ms)
0,12-08-2024,181.0,1454.5,4389.756115,88.933775,115.0,66.0,0.386543,0.478343,0.324931,10244.0,1.294051e+06
1,13-08-2024,180.0,1454.5,4193.930564,83.816770,105.0,66.0,0.415036,0.509161,0.313160,11040.0,1.265334e+06
2,14-08-2024,60.0,1454.5,1700.920657,85.792398,127.0,67.0,0.469593,0.469593,0.469593,10810.0,3.093364e+05
3,15-08-2024,61.0,1454.5,3015.839024,79.345745,118.0,57.0,0.417125,0.540696,0.293554,8100.0,1.025848e+06
4,17-08-2024,61.0,1454.5,1317.428951,84.850410,105.0,62.0,0.355202,0.355202,0.355202,8975.0,9.349274e+05